### ISSUE TITLE
Too few observation in ztf simulations 

### ISSUE THREAD

**Issue by nevencaplar** [nikhil-sarin/redback#183]
I believe the reason why there are [too few objects in the ZTF](https://github.com/nikhil-sarin/redback/pull/182#issuecomment-1704226621) survey simulations is because the[ pointings_database used for ZTF simulation](https://github.com/nikhil-sarin/redback/blob/master/redback/tables/ztf.tar.gz) is incomplete.

Given the ending date in pointings_database of August 31, 2022, I think the current database version is the DR14 release. The length of the pointings_database avaliable in redback is 106648. On the other hand, [the guide for the release](https://irsa.ipac.caltech.edu/data/ZTF/docs/releases/dr14/ztf_release_notes_dr14.pdf ) claims 713672 exposures.

I also see the median number of exposures per night in the poining_database is 92 and the median difference between exposure times (as specified in expMJD) is 0.004, which corresponds to 350 seconds. On the other hand, each exposure is 30 seconds, and I _believe_ that the expected cadence between exposure times should be around 40, 45 seconds. This leads me to the conclusion that this is only a pruned fraction of the data that should be available?

**Comment by nikhil-sarin** [comment]
Hi @nevencaplar - thanks for digging into this. This is a plausible source for the problem. I can have a look at the table but if this is indeed the problem, then the [rubin simulation](https://github.com/nikhil-sarin/redback/blob/master/examples/simulate_single_transient_in_rubin.py) which use the baseline v3.0 cadence should be more in line with what we expect. Pinging @cnsetzer here as he has a better understanding of Rubin simulations than me.

**Comment by nevencaplar** [comment]
Yes, rubin simulation looks fine and gives reasonable results as far as I can see.

**Comment by nikhil-sarin** [comment]
Thanks, Neven. There was indeed a problem with the ztf table (exactly the thing you described), which is resolved now. The new tables produces reasonable ZTF lightcurves and the rubin simulations also appear to be good, @cnsetzer is also doing some checks. Pull request #184 provides a fix with the new table but I'll wait till @cnsetzer is also happy to merge and do some additional testing myself. Long-term, simulation needs some sort of CI testing but I'll need to think of a good way to design a unit test for it.

**Comment by cnsetzer** [comment]
Hi both. Thanks for looping me in. I've taken a look now and I am satisfied to say that everything seems to be working as expected for the rubin simulations. Fine by me to close it, but I'll leave it to you.

**Comment by nikhil-sarin** [comment]
Great - thanks @cnsetzer

**Comment by nevencaplar** [comment]
Just a final thought here - it would be useful if the documentation or the docstrings would mention the origin of the ZTF and Rubin cadences - crucial if someone would like to cite/use this for research. At this point it is not clear to me where the base data is coming from (I did not do a deep dive though!)
