### ISSUE TITLE
Example GRB data gives Error

### ISSUE THREAD

**Issue by ZacharyLane1204** [nikhil-sarin/redback#192]
I am attempting to run the GRB example using private data in the tutorial and I keep getting the error "Meta data does not exist for this event." When I try to use my own personal data for a GRB (time, flux, flux_error) I also get the same error. Can you point me where to fix this or add a FAQ section to answer this?

**Comment by nikhil-sarin** [comment]
Hi @ZacharyLane1204, this 'error' is actually just a warning. Redback is currently set up to try and search for some metadata, redshift, RA/DEC of every transient when its first loaded from places like Swift and in future TNS. If it can't find this it will just throw this warning. When you create your own transient object it also does the same thing. 

The metadata is not necessary for any other functionality of redback so you are safe to ignore. 

Thanks for pointing this out as something to add to a FAQ. If you know how to do this and want to help me get started with one, please make a pull request!

**Comment by nikhil-sarin** [comment]
Closing as it's not an error. The warning message has been modified in #195
