### ISSUE TITLE
CSM Interaction Model not fitting

### ISSUE THREAD

**Issue by bradengarretson** [nikhil-sarin/redback#194]
I've been attempting to fit data using the csm_interaction model with the t0 and extinction models, but I can't seem to get it to work properly. I followed the example supernova_with_unknown_explosion_date.py exactly. It works perfectly fine on my own data if I use the arnett model, both when using my own data or when using the example data it doesn't, so I don't think it's on my end. 

Here is the outputs from me running the example exactly as is, except using the csm_interaction model and commenting out the arnett priors of course.

I've attached the cell input and output. The model runs extremely quickly for only a few iterations before it decides that it can't improve. It seems to me that there might be something either with the priors or the model itself? I've messed around with the infernce parameters and priors quite a bit and can't seem to get it to work. 

![image](https://github.com/nikhil-sarin/redback/assets/78453340/c5e46435-a916-40b1-a27d-de3ac8732a5b)

![image](https://github.com/nikhil-sarin/redback/assets/78453340/9a37e1dd-0b82-4227-889f-4794c822d419)

[output.txt](https://github.com/nikhil-sarin/redback/files/14325372/output.txt)
[input.txt](https://github.com/nikhil-sarin/redback/files/14325392/input.txt)

**Comment by nikhil-sarin** [comment]
Hi @bradengarretson - thanks for pointing this out. I suspect some samples from the default prior for the csm interaction model are producing nan outputs. I'll have a look. 

In the meantime, could you try running with kappa, r0, p, and mcsm fixed to a sensible value? I suspect it's some combination of these parameters allowed by the default prior that are blowing up the model and making inference fail.

**Comment by nikhil-sarin** [comment]
Hi @bradengarretson, did you figure this out? It turned out to be the wrong prior on rho in the default prior. I'll make a merge request tomorrow to fix this.

**Comment by nikhil-sarin** [comment]
fixed in #203
