### ISSUE TITLE
Numpy 2.0 not supported

### ISSUE THREAD

**Issue by DavidJLaw** [nikhil-sarin/redback#216]
numpy 2.0 gives import failure warning.

Suggest changing numpy in requirements.txt to 
numpy==1.26.4 

which will successfully resolve this.

**Comment by nikhil-sarin** [comment]
Hi @DavidJLaw, yep, thanks for flagging. I'm aware of this and will get the core package to be compatible with numpy 2.0 soonish. 

If you want to make a pull request with the suggested change in the meantime, I'm happy to merge it in to master.

**Comment by nikhil-sarin** [comment]
Thanks! 

PR #217 merged.

**Comment by nikhil-sarin** [comment]
#217 Breaks the docs

**Comment by nikhil-sarin** [comment]
#218 fix
