### ISSUE TITLE
`pip install redback` does not install dependencies

### ISSUE THREAD

**Issue by robertdstein** [nikhil-sarin/redback#224]
I tried installing `redback` via pip in a completely clean environment, as suggested here (https://redback.readthedocs.io/en/latest/installation.html), which seemed to work fine. However, after trying to `import redback`, I get an import error for a dependency (`matplotlib` in this case). Checking `pip list`, I see that only redback itself gets installed, but none of the dependencies.

Looking at https://github.com/nikhil-sarin/redback/blob/master/setup.py, I could not see where the dependencies listed in https://github.com/nikhil-sarin/redback/blob/master/requirements.txt actually get passed to the setup script. It's the same story if I clone the repo directly and try `pip install .` .

For `setup.py` you need to explicitly add an argument `install_requires` in order for the dependencies to be installed. Until then, `pip install redback` ( and `pip install .` with a local copy) will not actually work properly.

**Comment by nikhil-sarin** [comment]
Thanks for catching this Rob. I'll fix this but won't get to it till next week. 

If you are installing from source (which I recommend you do), then do `pip install -r requirements.txt` first and it will work.

**Comment by nikhil-sarin** [comment]
Just saw your pull, thanks for doing that.
