### ISSUE TITLE
Open Transient Catalogue data scrape met with bad SSL certificate

### ISSUE THREAD

**Issue by GPLamb** [nikhil-sarin/redback#245]
e.g., the SN1998bw example -- homologous vs arnett model and SN1998bw data returns:
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.astrocats.space', port=443): Max retries exceeded with url: /SN1998bw/photometry/time+magnitude+e_magnitude+band+system?e_magnitude&band&time&format=csv (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))

Tested on two independent machines -- MacBook, and Dell Ubuntu. Same same -- webbrowser can get to data but with warnings (not safe)

**Comment by nikhil-sarin** [comment]
@GPLamb this isn't a redback issue but a OAC API one. Nothing I can do with redback.
